use serde::Serialize;

/// A name candidate generated by one or more LLMs.
#[derive(Debug, Clone, Serialize)]
pub struct NameCandidate {
    pub name: String,
    pub suggested_by: Vec<String>,
}

/// Compact domain availability summary.
#[derive(Debug, Clone, Serialize)]
pub struct DomainSummary {
    pub available: usize,
    pub registered: usize,
    pub unknown: usize,
    pub total: usize,
    pub details: Vec<DomainDetail>,
}

#[derive(Debug, Clone, Serialize)]
pub struct DomainDetail {
    pub domain: String,
    pub available: String,
}

/// Compact package registry availability summary.
#[derive(Debug, Clone, Serialize)]
pub struct PackageSummary {
    pub available: usize,
    pub taken: usize,
    pub unknown: usize,
    pub total: usize,
    pub details: Vec<PackageDetail>,
}

#[derive(Debug, Clone, Serialize)]
pub struct PackageDetail {
    pub registry: String,
    pub available: String,
}

/// A fully-checked name with score and availability details.
#[derive(Debug, Clone, Serialize)]
pub struct NameResult {
    pub name: String,
    pub score: f64,
    pub suggested_by: Vec<String>,
    pub domains: DomainSummary,
    pub packages: PackageSummary,
}

/// The full output of a find_names or check_names operation.
#[derive(Debug, Clone, Serialize)]
pub struct AvailableResult {
    pub results: Vec<NameResult>,
    pub models_used: Vec<String>,
    pub errors: Vec<GenerationError>,
}

/// Records a per-model generation failure.
#[derive(Debug, Clone, Serialize)]
pub struct GenerationError {
    pub model: String,
    pub error: String,
}

/// Configuration for name generation and checking.
#[derive(Debug, Clone)]
pub struct Config {
    pub tlds: Vec<String>,
    pub registry_ids: Vec<String>,
    pub max_names: usize,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            tlds: vec!["com".into(), "dev".into(), "io".into()],
            registry_ids: vec![],
            max_names: 20,
        }
    }
}
